apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: whereami
patchesJson6902:
- target:
    kind: Deployment
    name: whereami
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: us-east4-docker.pkg.dev/acm-workshop-743-tenant/containers/whereami:v1.2.8
- target:
    kind: VirtualService
    name: whereami
  patch: |-
    - op: replace
      path: /spec/hosts
      value:
        - whereami.endpoints.acm-workshop-743-tenant.cloud.goog
