apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: whereami
patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/hosts
      value:
        - whereami.endpoints.acm-workshop-743-tenant.cloud.goog
  target:
    kind: VirtualService
    name: whereami
images:
- name: whereami
  newName: us-east4-docker.pkg.dev/acm-workshop-743-tenant/containers/whereami
  newTag: v1.2.8
